add tab count badge
RJHsiao/ListOpenedTabs pull request #11
Opened 2019-05-10 07:54 UTC by insaner

Please let me know if I did this right, I'm just starting to figure out how github/git work.

2019-07-25 12:47 UTC, RJHsiao requested changes
Please try to resolve about following comments.

2019-07-25 12:47 UTC, RJHsiao commented on manifest.json
> +
Please remove empty line

2019-07-25 12:47 UTC, RJHsiao commented on js/eventPage.js
> +    // chrome.tabs.query({},
Please remove unused code (Lin5), empty lines (L7 & L9), and align indent (L6~12).

2019-08-10 08:57 UTC, insaner commented
Ok, I hope I did it right. Everything should look ok now.

2019-08-13 12:56 UTC, RJHsiao approved these changes

2019-08-13 12:57 UTC, merged

2019-08-13 12:58 UTC, RJHsiao commented
Well done!

2019-08-13 21:06 UTC, insaner commented
Awesome! Thank you!